### ISSUE TITLE
Requesting api-review of schema: core-dns operator

### ISSUE THREAD

**Issue by justinsb** [kubernetes-sigs/addon-operators#23]
This is an issue to request API review of our addon operator schema.  We now have an example addon operator for CoreDNS that is our current thinking:
https://github.com/kubernetes-sigs/addon-operators/blob/master/coredns/config/crds/addons_v1alpha1_coredns.yaml

/label api-review

**Comment by smarterclayton** [comment]
The status section should be more consistent with our existing object structure.  I would suggest using conditions rather than make up a new status reporting field `errors` and follow the generic conventions for condition as described in https://github.com/eBay/Kubernetes/blob/master/docs/devel/api-conventions.md#typical-status-properties

**Comment by smarterclayton** [comment]
For channel and version, are those likely to be shared across a number of similar objects?  If so, you should probably document a mini-spec explaining what those are, how they should be used, what the format of version is, and what clients that don't support whatever your form of version should do.

**Comment by smarterclayton** [comment]
If this request is still valid let's set up a time to do an api review.
